### ISSUE TITLE
Scriptable Render Pipeline support

### ISSUE THREAD

**Issue by Adiwan** [ExtendRealityLtd/Zinnia.Unity#410] opened 2019-06-21 06:10 UTC
Unity showcased their Lightweight Render Pipeline working with VR so many people will try to use Zinnia (and VRTK) for their projects but they will encounter various incompatibilities.

For example:
In the class CameraColorOverlay there is a use of the camera event onPostRender, which isn't supported by the Scriptable Render Pipeline. Unity does not throw an error or a warning whenever the camera events are used when a Scriptable Render Pipeline asset is used.

### Environment
* Version of VRTKv4: Branch Master c711898f6cba7b8e10bfcf29204a8e5aa95ea859
* Version of Zinnia: Branch Master fff23cddc224a084be61214108a390c7032095f4
* Version of the Unity: Unity 2018.3.10f1
* Version of the Lightweight Render Pipeline: 4.10

### Steps to reproduce
Created a new project.
Added the Lightweight Render Pipeline from the Package Manager.
Set the LWRP asset in the Graphics settings.
Added VRTK and Zinnia to the Project.
Used the Simulated Camera Rig in the Farm example scene from VRTK (because the XR Camera Rig camera was black and the tracked alias controllers did not move)
Moved the rig into a building.

### Expected behavior
The same functionality as in without the use of the Scriptable Render Pipeline.
In the case of the Camera Color Overlay I expected a fade to black in the camera.

### Current behavior
In the case of the Camera Color Overlay no color overlay occurs.

**Comment by thestonefox** [comment] 2019-06-21 06:17
Duplicate of https://github.com/ExtendRealityLtd/VRTK/issues/1959

**Closed by thestonefox** 2019-06-21 06:17 UTC
