### ISSUE TITLE
ValueExtractor has some edge cases breaking IL2CPP builds

### ISSUE THREAD

**Issue by Bullrich** [ExtendRealityLtd/Zinnia.Unity#498] opened 2020-04-27 17:28 UTC
### Environment

* Code source: Package manager
* Code version: "io.extendreality.zinnia.unity": "1.16.0"
* Platform version: Unity 2019.2.21f1
* 3rd party dependencies: None

### Steps to reproduce

- Create a new project,
- Add a script to the main scene that does the following
```csharp
using UnityEngine;
using Zinnia.Data.Operation.Extraction;

public class Example : MonoBehaviour
{
    void Start()
    {
        // We force the type to appear
        Debug.Log(typeof(SurfaceDataCollisionPointExtractor));
    }
}
```
- Save the scene
- Set scripting backend to IL2CPP and build

### Expected behavior

Should build.

### Current behavior

IL2CPP compilation error.

It seems that `ValueExtractor` has some edge cases that breaks the AOT scripting restrictions causing the build to fail.

I tried setting Stripping level to high and it still won't build.

Also, the class that I used to reproduce the error is `SurfaceDataCollisionPointExtractor`, but some other classes, like `SurfaceDataCollisionDataExtractor` don't cause this problem, so it seems to be a problem with the type `RaycastHit`.

Part of the log which seems useful says: 
> error C2440: 'type cast': cannot convert from 'int' to RaycastHit_t19695F18F9265FE5425062BBA6A4D330480538C3'

**Comment by WalternativE** [comment] 2020-04-29 15:19
Did some further investigation on this issue. I first went down the first route and assumed that it had something to do with stripping. I tried to add a `link.xml` file to preserve the whole `Zinnia.Runtime` assembly. When that didn't work I directly added the `Preserve` attribute to the `ValueExtractor` class in the plugin code. Both attempts didn't change the results.

After further digging I'm pretty sure that stripping isn't the problem but rather IL2CPP not generating the right overload for the generic call of `ValueExctractor<T, T1, T2, T3>::ClearSource`. There are overloads for `ValueExtractor` variants with the source type of `RayCastHit` but not for `int`. This might be the cause of some IL2CPP/ILWeaving clashes. The project was buildable again after modifying the `ValueExtractor` class and deleting the Malimbe `Cleared` attribute from the `Source` property - naturally this has more implications and is therefore not a good workaround.

I used the VR Bowling tutorial (great guide, btw ❤) to reproduce the issue. The current state of this [repository](https://github.com/WalternativE/VrBowlingExample) works for IL2CPP. Updating the `io.extendreality.tilia.interactions.interactables.unity` package to 1.7.x begins to introduce problems. I assume that this could be connected to the Zinnia update from 1.14.1 to 1.15.0 but at this point I'm guessing.

**Comment by hawkwood** [comment] 2020-05-11 23:57
In my limited use case, I found that deleting all io.extendreality.zinnia.unity@1.16.0/Runtime/Data/Operation/Extraction/RaycastHit*Extractor.cs files allowed me to compile again.

**Comment by FireDragonGameStudio** [comment] 2020-05-15 22:02
Any updates on this? Same problem here -.-

**Comment by hawkwood** [comment] 2020-05-20 15:27
I opened a case with Unity and just got the following response:

—-

It looks like there is invalid IL code in Zinnia.Runtime.dll. The problem happens in the Zinnia.Data.Operation.Extraction.ValueExtractor<TResultElement,TSourceElement,TEvent,TEventElement>.ClearSource method. In this case, TSourceElement is UnityEngine.RaycastHit. The C# code for ClearSource (from ILSpy) is:

[CompilerGenerated]
public void ClearSource()
{
   Source = (TSourceElement)null;
}

Since UnityEngine.RaycastHit is a struct, it is not nullable, and therefore cannot be set to a value of null.

I don't believe this is something we can correct on the Unity side.

**Comment by thestonefox** [comment] 2020-05-20 15:33
This is auto generated by Malimbe.

@bddckr is it possible to have the `MemberClearanceMethod` set the field to `default` instead of `null`?

**Comment by bddckr** [comment] 2020-05-20 15:46
Malimbe's `MemberClearanceMethod` only supports reference types currently. Adding `default` support is not trivial, which is why I never did it, [see this](https://stackoverflow.com/questions/10400358/how-to-translate-defaultsometype-from-c-sharp-to-cil).

**Comment by thestonefox** [comment] 2020-05-20 15:48
In this case then, probably best to just override the `ClearSource` method in the `ValueExtractor` so it can manually just set it to `default`

**Comment by bddckr** [comment] 2020-05-20 16:03
That should do it! Might be a good time to check all the other attribute usages, too.

We actually already guard against this [here](https://github.com/ExtendRealityLtd/Malimbe/blob/c2ea3fe3e304f6bc142bb34503886f6909a6639e/Sources/MemberClearanceMethod.Fody/ModuleWeaver.cs#L66-L72). I wonder why that doesn't show as an error in this case? It should log the error text and actually skip the method generation for that field completely as you can see.

**Comment by thestonefox** [comment] 2020-05-20 16:05
Maybe because it's in the abstract class?

**Comment by bddckr** [comment] 2020-05-20 16:11
Hmm there might be the need to go from that type reference to something else first perhaps, via one of its properties. Not sure.

**Comment by thestonefox** [comment] 2020-05-20 16:13
I'll just fix it by overriding it for now, i'll look for any other cases where this could occur too. Pretty much any generic class that uses Cleared on a generic type.

**Comment by hawkwood** [comment] 2020-05-21 16:41
So what is the suggested workaround for us mere mortals as you integrate this into the package?

**Comment by thestonefox** [comment] 2020-05-21 16:45
wait for this to be merged: https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/499

**Comment by thestonefox** [comment] 2020-05-22 06:31
This PR has now been merged, so the issue in Zinnia is fixed.

The Tilia repos will be updated to the latest version of Zinnia.

Please note that VRTK.Prefabs will not receive any Zinnia updates as there may be compatibility issues so you'll have to apply this fix manually.

**Comment by FireDragonGameStudio** [comment] 2020-05-22 08:09
Sry to ruin the mood @thestonefox, but it's still not working when building for Quest (Android Build with IL2CPP, .NET4.
[Zinnia_IL2CPP_ErrorLog.txt](https://github.com/ExtendRealityLtd/Zinnia.Unity/files/4666835/Zinnia_IL2CPP_ErrorLog.txt)
x, ARM64). My test project only uses the Zinnia package 1.17.0. Please find the full error log attached.

```
...
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException:
D:\UnityProjects\ZinniaTest\Temp\StagingArea\Il2Cpp\il2cppOutput\Generics12.cpp:17365:297:
error: no matching conversion for C-style cast from 'long' to
'RaycastHit_t19695F18F9265FE5425062BBA6A4D330480538C3'
...
```

**Comment by thestonefox** [comment] 2020-05-22 08:23
@FireDragonGameStudio can you do a test for me:

in every Extractor that has the `RaycastHit` as the `Source` (which is most likely all `Data/Operation/Extraction/RaycastHit*`

just add a override ClearSource method of:

```
/// <inheritdoc />
public override void ClearSource()
{
    Source = new RaycastHit();
}
```

I'm guessing that Unity is crapping out because it can't do `Source = default` for a RaycastHit

**Comment by Bullrich** [comment] 2020-05-22 08:38
@thestonefox I'm afraid I can still reproduce the problem using the same steps at beginning of the issue.

I also tried to use `RaycastHitPointExtractor` instead of `SurfaceDataCollisionPointExtractor` because I got the Depecrated warning and it still fails when building with IL2CPP.

**Comment by thestonefox** [comment] 2020-05-22 08:39
@Bullrich try the steps I outlined to @FireDragonGameStudio and report the results

**Comment by FireDragonGameStudio** [comment] 2020-05-22 08:41
Sry @thestonefox, the IL2CPP build error is still present, after adding the override to the `RaycastHit*` files.

**Comment by thestonefox** [comment] 2020-05-22 08:43
Are you getting the same error?

**Comment by Bullrich** [comment] 2020-05-22 08:45
@thestonefox I tried it and still have the same problem

> error C2440: 'type cast': cannot convert from 'int' to 'RaycastHit_t19695F18F9265FE5425062BBA6A4D330480538C3'

**Comment by FireDragonGameStudio** [comment] 2020-05-22 08:45
Yes, I'll pls find the log attached to this comment.
[Zinnia_IL2CPP_ErrorLog.txt](https://github.com/ExtendRealityLtd/Zinnia.Unity/files/4666995/Zinnia_IL2CPP_ErrorLog.txt)

**Comment by thestonefox** [comment] 2020-05-22 09:09
Can you try in the `ValueExtractor.cs` file on line `23` removing the `Cleared` flag

so it just reads:

```
[Serialized]
[field: DocumentedByXml]
public TSourceElement Source { get; set; }

```

**Comment by FireDragonGameStudio** [comment] 2020-05-22 09:17
That seemed to did the trick @thestonefox :) Build was successful

**Comment by thestonefox** [comment] 2020-05-22 09:30
@bddckr do you have any guesses as to why keeping `Cleared` in would be causing the issue?

I thought if you overrode the method then Malimbe wouldn't attempt to weave it. But in this case I'm guessing that Malimbe is seeing the method and overriding the one that was manually set.

The fix can be just to remove the Cleared attribute, but I want to just make sure Malimbe is working as expected.

**Comment by bddckr** [comment] 2020-05-22 09:53
That's expected and on purpose:
https://github.com/ExtendRealityLtd/Malimbe/blob/c2ea3fe3e304f6bc142bb34503886f6909a6639e/Sources/MemberClearanceMethod.Fody/ModuleWeaver.cs#L80-L83

This allows one to add *additional* logic to the method, while keeping the auto-injected logic from Malimbe.

So yeah, you need to remove the attribute if you want to *replace* Malimbe's logic.

**Comment by thestonefox** [comment] 2020-05-22 09:55
@bddckr ok cool, as long as it's expected. I'll raise a PR with this fix in

**Comment by extendreality** [comment] 2020-05-22 10:03
Pull request with fix: https://github.com/ExtendRealityLtd/Zinnia.Unity/pull/500

**Closed** 2020-05-22 13:36 UTC

**Comment by Bullrich** [comment] 2020-05-22 14:44
I just tried with the new version and couldn't replicate the issue anymore. Thank you very much for the fix!
